### ISSUE TITLE
[BUG] Evaluation bug in eval.py compute_depth_metrics()

### ISSUE THREAD

**Issue by huangxGo** [MichaelRamamonjisoa/SharpNet#10]
Thank for this wonderful work!
I believe there is a bug in this line of code.
https://github.com/MichaelRamamonjisoa/SharpNet/blob/6d69dcdf8dbffc82c5973054cef868cbfccd33e6/eval.py#L56
May be the **RMSElog**  is natural logarithm instead of log10?

**Comment by MichaelRamamonjisoa** [comment]
Thank you! Changing from log10 to log would not change the ranking of different methods we evaluated, but numerical values could differ. 
However, looking at the [DORN](https://github.com/hufu6371/DORN) paper and especially its evaluation code score_nyuv2.m (downloaded [here](https://drive.google.com/open?id=1uRqOkCbJLwHWyx4oz19N6MQgrOSZQo6H) ), they have the following:

```
C = abs(log10(A) - log10(B));
depth_score(7, i) = sum(C(:))/N;
```
Do you have examples of benchmarks natural log is used instead?

**Comment by huangxGo** [comment]
> Thank you! Changing from log10 to log would not change the ranking of different methods we evaluated, but numerical values could differ.
> However, looking at the [DORN](https://github.com/hufu6371/DORN) paper and especially its evaluation code score_nyuv2.m (downloaded [here](https://drive.google.com/open?id=1uRqOkCbJLwHWyx4oz19N6MQgrOSZQo6H) ), they have the following:
> 
> ```
> C = abs(log10(A) - log10(B));
> depth_score(7, i) = sum(C(:))/N;
> ```
> 
> Do you have examples of benchmarks natural log is used instead?

Thank for your reply!I think you're right.I thought the RMSElog should be same as this line.
https://github.com/MichaelRamamonjisoa/SharpNet/blob/6d69dcdf8dbffc82c5973054cef868cbfccd33e6/eval.py#L69
It seems that it's not.As the paper and code you mentioned above, there is a little difference between 2 line of the evaluation code.And I will close this issue!
