### ISSUE TITLE
What's the --scale option means when run the demo.py? 

### ISSUE THREAD

**Issue by LiZhenLiangLee** [MichaelRamamonjisoa/SharpNet#12]
If the size of my input image is not 640x480, can you tell me how to set the --scale option ？an example？

**Comment by LiZhenLiangLee** [comment]
And the --scale set to 1.0 if input image's size is 640x480, right?

**Comment by MichaelRamamonjisoa** [comment]
Hi, thanks for your interest!
The scale option is a scale factor applied to the original dimensions of the image. 
If your input image size is 1280x960, using --scale 0.5 would scale it down to 640x480.
If your input image size is 320x240, using --scale 2 would scale it up to 640x480.

Generally, if you set --scale S, S being a float number, and your original resolution is WxH, the rescaled input (and output) will be of size SW x SH.

**Comment by LiZhenLiangLee** [comment]
> Hi, thanks for your interest!
> The scale option is a scale factor applied to the original dimensions of the image.
> If your input image size is 1280x960, using --scale 0.5 would scale it down to 640x480.
> If your input image size is 320x240, using --scale 2 would scale it up to 640x480.
> 
> Generally, if you set --scale S, S being a float number, and your original resolution is WxH, the rescaled input (and output) will be of size SW x SH.

thanks for reply
