### ISSUE TITLE
How to get  the real absolute depth from your model ?

### ISSUE THREAD

**Issue by LiZhenLiangLee** [MichaelRamamonjisoa/SharpNet#13]
I found the following code in file 'demo.py'
` depth_pred = depth_pred.data.cpu().numpy()[0, 0, ...] * 65535 / 1000`

and I think the depth_pred is the real depth in meters, right?

**Comment by MichaelRamamonjisoa** [comment]
You are correct! Using this denormalization, depth is expressed in meters.

**Comment by LiZhenLiangLee** [comment]
> You are correct! Using this denormalization, depth is expressed in meters.

ok, thanks!
