### ISSUE TITLE
Strange Output Artefacts

### ISSUE THREAD

**Issue by huberthomas** [MichaelRamamonjisoa/SharpNet#6]
![sharpnet_bsds500_16068](https://user-images.githubusercontent.com/50195949/61850147-cd677800-aeb3-11e9-85ff-71225884cec0.png)
Reference: BSDS500, subset test. Order: 1st row - RGB, Depth, 2nd row - Boundary, Normals

I tried out the BSDS500 dataset (https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/resources.html) and got these artefacts always in the left bottom in about 20% of 200 images from the test subset.

**Comment by MichaelRamamonjisoa** [comment]
Hi, I noticed this bug. Please try using the new version of weights. For contour detection, I recommend using pretrained weights on PBRS only.

**Comment by huberthomas** [comment]
Thank you very much!
