### ISSUE TITLE
[Question] Do you have any result or plan on KITTI

### ISSUE THREAD

**Issue by HongxingGao** [MichaelRamamonjisoa/SharpNet#7]
Hi, Michael, 

Nice idea and great work! I am wondering if you have result of KITTI. Or do you plan to further work on KITTI?

Thanks

**Comment by MichaelRamamonjisoa** [comment]
Hello,

Thanks for your interest ! We are considering working on KITTI, however, the requirement would be to have a large enough synthetic dataset to learn geometry on KITTI then use the same fine-tuning process on KITTI. Therefore it is not yet decided whether the method is directly applicable or not. But we are currently working on KITTI for other projects so chances are we may put some results with SharpNet or modified version of SharpNet.
