### ISSUE TITLE
About the depth-boundary consistency loss

### ISSUE THREAD

**Issue by sunnyHelen** [MichaelRamamonjisoa/SharpNet#8]
Thank you for sharing your great work. 
I have one question about the implementation of your loss function. For depth-boundary consistency loss, I think you realize it as a class there. But I found it isn't the same as the formulation you use in your paper. It seems like one the first term and without a minus sign. I'm a little confused and please help me figure it out.
![image](https://user-images.githubusercontent.com/28101548/63587173-8ec5fa00-c5e6-11e9-95d1-af34d976b9b8.png)
https://github.com/MichaelRamamonjisoa/SharpNet/blob/9206fb0f42c4d3dbc78dd6fcce7d6f965d645128/loss.py#L266

**Comment by MichaelRamamonjisoa** [comment]
Hello,
Indeed, you are right, the loss I put in my code was a previous version, I will update it shortly. Thank you for your notice !

**Comment by MichaelRamamonjisoa** [comment]
I solved this issue in commit 18672e11c26a95efb4843662f045c3bfa5082d47, minus signs may be written with torch.abs but they are the same in the end as terms are non positive.
