### ISSUE TITLE
Question: Annotation tool

### ISSUE THREAD

**Issue by tim885** [MichaelRamamonjisoa/SharpNet#9]
I noted that you manually annotated 100 NYUv2 images with occlusion contours. Can you kindly tell me which tool did you use for annotation? Thanks a lot!

**Comment by MichaelRamamonjisoa** [comment]
Hi, I used the Guoxia Wang's [Instance Labeling tool](https://github.com/GuoxiaWang/InstanceLabelTool). It is nice to compute closed occlusion contours, but requires a bit of tricks to compute non-close contours.

**Comment by tim885** [comment]
Thanks  for your response, I tried Instance Labeling tool and it works! For non-close contours, the way I found out is make instance polygons extremely thin and then convert it to boundary. Is that correct?

**Comment by MichaelRamamonjisoa** [comment]
Yes I'm doing exactly that. It is a bit more time consuming but it all works out.
